import axios from 'axios';
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

const DashboardScreen = () => {
  const navigate = useNavigate();
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [dropdownOpen, setDropdownOpen] = useState(false);

  const fetchData = async () => {
    try {
      const response = await axios.get(`${process.env.REACT_APP_BACKEND_APP_URL}/api/inscriptions`, {
        headers: {
          Authorization: `Bearer ${localStorage.getItem('accessToken')}`,
        },
      });
      setData(response.data.data);
    } catch (err) {
      console.error(err);
      setError('Failed to fetch data. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const accessToken = localStorage.getItem('accessToken');
    if (!accessToken) {
      navigate('/');
    } else {
      fetchData();
    }
  }, [navigate]);

  const handleLogout = () => {
    localStorage.removeItem('accessToken');
    navigate('/');
  };

  const toggleDropdown = () => {
    setDropdownOpen((prev) => !prev);
  };

  const exportToExcelForItem = (item) => {
    const worksheetData = [
      { Name: `${item.first_name} ${item.last_name}`, City: item.city, Speciality: item.speciality, Phone: item.phone, Email: item.email, InPersonParticipation: item.in_person ? 'Yes' : 'No', CertificateNeeded: item.certificate ? 'Yes' : 'No' },
    ];
    const worksheet = XLSX.utils.json_to_sheet(worksheetData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Inscription Details');
    XLSX.writeFile(workbook, `${item.first_name}_${item.last_name}_Details.xlsx`);
  };

  const generatePDFForItem = (item) => {
    const doc = new jsPDF();
  
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text('Inscription Details', 10, 10);
    
    doc.setFontSize(12);
    doc.text('', 10, 15);
  
    doc.setFont("helvetica", "normal");
    
    const details = [
      { label: 'Name:', value: `${item.first_name} ${item.last_name}` },
      { label: 'City:', value: item.city },
      { label: 'Speciality:', value: item.speciality },
      { label: 'Phone:', value: item.phone },
      { label: 'Email:', value: item.email },
      { label: 'Participation en présentiel ? :', value: item.in_person ? 'Yes' : 'No' },
      { label: '', value: '', break: true },
      { label: "Attestation nécessaire ? :", value: item.certificate ? 'Yes' : 'No' },
      { label: '', value: '', break: true },
    ];
  
    let yPosition = 30;
    details.forEach(detail => {
      doc.setFont("helvetica", "bold");
      doc.text(detail.label, 10, yPosition);
      doc.setFont("helvetica", "normal");
      doc.text(detail.value, 70, yPosition);
      
      if (detail.break) {
        yPosition += 15;
      } else {
        yPosition += 10;
      }
    });
  
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Generated by Société Marocaine de Diabétologie', 10, yPosition + 20);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 10, yPosition + 25);
  
    doc.save(`${item.first_name}_${item.last_name}_Details.pdf`);
  };
      
  return (
    <div className='container mx-auto py-12 px-6'>
      {/* Header */}
      <header className='flex justify-between items-center bg-gray-800 p-5 rounded-lg shadow-md text-white'>
        <h1 className='text-xl font-bold'>Dashboard</h1>
        <div className='relative'>
          <button
            onClick={toggleDropdown}
            className='bg-red-500 px-3 py-2 rounded-full shadow-lg hover:bg-red-600 focus:outline-none'
          >
            <i className="fa-solid fa-right-from-bracket text-white"></i>
          </button>
          {dropdownOpen && (
            <div className='absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg z-10'>
              <div className='py-3 px-4 text-gray-800 text-sm'>
                <p>Are you sure you want to log out?</p>
              </div>
              <div className='flex border-t border-gray-200'>
                <button
                  onClick={handleLogout}
                  className='w-full py-2 text-center text-red-600 hover:bg-red-100'
                >
                  Yes, Log out
                </button>
                <button
                  onClick={toggleDropdown}
                  className='w-full py-2 text-center text-gray-600 hover:bg-gray-100'
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      </header>

      {/* Cards List */}
      <div className='grid gap-8 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mt-10 px-4'>
        {loading && <p className='text-center text-gray-500'>Loading...</p>}
        {error && <p className='text-center text-red-500'>{error}</p>}
        {data.map((item) => (
          <div key={item.id} className='bg-white p-6 rounded-lg shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl border border-gray-200'>
            <h2 className='text-2xl font-semibold mb-3 text-gray-800'>{item.first_name} {item.last_name}</h2>
            <p className='text-gray-600'><strong>City:</strong> {item.city}</p>
            <p className='text-gray-600'><strong>Speciality:</strong> {item.speciality}</p>
            <p className='text-gray-600'><strong>Phone:</strong> {item.phone}</p>
            <p className='text-gray-600'><strong>Email:</strong> {item.email}</p>
            <p className='text-gray-600'><strong>In-person Participation:</strong> {item.in_person ? 'Yes' : 'No'}</p>
            <p className='text-gray-600'><strong>Certificate Needed:</strong> {item.certificate ? 'Yes' : 'No'}</p>

            <div className='flex justify-between mt-4'>
              <button
                onClick={() => generatePDFForItem(item)}
                className='bg-blue-500 text-white py-2 px-4 rounded-lg shadow hover:bg-blue-600 transition duration-200 mr-2 flex items-center'
              >
                <strong>PDF</strong> <i className="fa-solid fa-file-pdf fa-fade text-lg mx-2"></i>
              </button>
              <button
                onClick={() => exportToExcelForItem(item)}
                className='bg-green-500 text-white py-2 px-4 rounded-lg shadow hover:bg-green-600 transition duration-200 flex items-center'
              >
                <strong>EXCEL</strong> <i className="fa-solid fa-table fa-fade text-lg mx-2"></i>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DashboardScreen;
