import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';
import { inscriptionAction } from '../redux/actions/InscriptionAction';
import { useDispatch, useSelector } from "react-redux";

const DashboardScreen = () => { 
  const navigate = useNavigate();
  const dispatch = useDispatch();
  const [searchTerm, setSearchTerm] = useState('');  // State for search term

  const { data, loading, error } = useSelector((state) => state.inscription);

  useEffect(() => {
    const accessToken = localStorage.getItem('accessToken');

    if (!accessToken) {
      navigate('/');
    } else {
      dispatch(inscriptionAction());
    }
  }, [navigate, dispatch]);

  // Handle search input change
  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value);
  };

  // Filter data based on search term
  const filteredData = data.filter((item) =>
    `${item.first_name} ${item.last_name}`.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const exportToExcelForItem = (item) => {
    const worksheetData = [
      { Name: `${item.first_name} ${item.last_name}`, City: item.city, Speciality: item.speciality, Phone: item.phone, Email: item.email, InPersonParticipation: item.in_person ? 'Yes' : 'No', CertificateNeeded: item.certificate ? 'Yes' : 'No' },
    ];
    const worksheet = XLSX.utils.json_to_sheet(worksheetData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Inscription Details');
    XLSX.writeFile(workbook, `${item.first_name}_${item.last_name}_Details.xlsx`);
  };

  const generatePDFForItem = (item) => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text('Inscription Details', 10, 10);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const details = [
      { label: 'Nom:', value: `${item.first_name} ${item.last_name}` },
      { label: 'Ville:', value: item.city },
      { label: 'Spécialité:', value: item.speciality },
      { label: 'Téléphone:', value: item.phone },
      { label: 'E-mail:', value: item.email },
      { label: 'Participation en présentiel ? :', value: item.in_person ? 'Yes' : 'No' },
      { label: "Attestationné nécessaire ? :", value: item.certificate ? 'Yes' : 'No' },
    ];

    let yPosition = 30;
    details.forEach(detail => {
      doc.setFont("helvetica", "bold");
      doc.text(detail.label, 10, yPosition);
      doc.setFont("helvetica", "normal");
      doc.text(detail.value, 70, yPosition);
      yPosition += 10;
    });

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text('Generated by Société Marocaine de Diabétologie', 10, yPosition + 20);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 10, yPosition + 25);

    doc.save(`${item.first_name}_${item.last_name}_Details.pdf`);
  };

  const exportAllInscriptionsToPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text('Inscriptions List', 10, 10);

    let yPosition = 20;
    filteredData.forEach((item, index) => {
      doc.setFontSize(14);
      doc.text(`${index + 1}. ${item.first_name} ${item.last_name}`, 10, yPosition);
      yPosition += 10;

      const details = [
        { label: 'Ville:', value: item.city },
        { label: 'Spécialité:', value: item.speciality },
        { label: 'Téléphone:', value: item.phone },
        { label: 'E-mail:', value: item.email },
        { label: 'Participation en présentiel ? :', value: item.in_person ? 'Yes' : 'No' },
        { label: "Attestation nécessaire ? :", value: item.certificate ? 'Yes' : 'No' },
      ];

      details.forEach(detail => {
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.text(`${detail.label} ${detail.value}`, 20, yPosition);
        yPosition += 8;
      });

      yPosition += 10;
      if (yPosition > 280) { 
        doc.addPage();
        yPosition = 20;
      }
    });

    doc.save('Inscriptions_List.pdf');
  };

  const exportAllInscriptionsToExcel = () => {
    const worksheetData = filteredData.map(item => ({
      Name: `${item.first_name} ${item.last_name}`,
      City: item.city,
      Speciality: item.speciality,
      Phone: item.phone,
      Email: item.email,
      InPersonParticipation: item.in_person ? 'Yes' : 'No',
      CertificateNeeded: item.certificate ? 'Yes' : 'No',
    }));

    const worksheet = XLSX.utils.json_to_sheet(worksheetData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Inscriptions List');
    XLSX.writeFile(workbook, 'Inscriptions_List.xlsx');
  };

  return (
    <div className="container mx-auto py-12 px-6">
      <div className="mb-8 my-10">
        <input 
          type="text" 
          placeholder="Search by name..." 
          value={searchTerm} 
          onChange={handleSearchChange} 
          className="border p-2 rounded w-full"
        />
      </div>

      <div className="flex justify-center gap-4 mb-8">
        <button
          onClick={exportAllInscriptionsToPDF}
          className="bg-blue-500 text-white py-2 px-4 rounded-lg shadow hover:bg-blue-600 transition duration-200 flex items-center"
        >
          <strong>PDF Export</strong> <i className="fa-solid fa-file-pdf text-lg mx-2"></i>
        </button>
        <button
          onClick={exportAllInscriptionsToExcel}
          className="bg-green-500 text-white py-2 px-4 rounded-lg shadow hover:bg-green-600 transition duration-200 flex items-center"
        >
          <strong>Excel Export</strong> <i className="fa-solid fa-table text-lg mx-2"></i>
        </button>
      </div>

      <div className="grid gap-8 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mt-10 px-4">
        {loading && <p className="text-center text-gray-500">Loading...</p>}
        {error && <p className="text-center text-red-500">{error}</p>}
        {filteredData.map((item) => (
          <div key={item.id} className="bg-white p-6 rounded-lg shadow-lg transition-transform transform hover:scale-105 hover:shadow-2xl border border-gray-200">
            <h2 className="text-2xl font-semibold mb-3 text-gray-800">{item.first_name.slice(0, 30) + (item.first_name.length > 30 ? '...' : '')} {item.last_name.slice(0, 30) + (item.last_name.length > 30 ? '...' : '')}</h2>
            <p className="text-gray-600"><strong>Ville:</strong> {item.city.slice(0, 30) + (item.city.length > 30 ? '...' : '')}</p>
            <p className="text-gray-600"><strong>Spécialité:</strong> {item.speciality.slice(0, 30) + (item.speciality.length > 30 ? '...' : '')}</p>
            <p className="text-gray-600"><strong>Téléphone:</strong> {item.phone.slice(0, 30) + (item.phone.length > 30 ? '...' : '')}</p>
            <p className="text-gray-600"><strong>E-mail:</strong> {item.email.slice(0, 30) + (item.email.length > 30 ? '...' : '')}</p>
            <p className="text-gray-600"><strong>Participation en présentiel ?:</strong> {item.in_person ? 'Yes' : 'No'}</p>
            <p className="text-gray-600"><strong>Attestation nécessaire ?:</strong> {item.certificate ? 'Yes' : 'No'}</p>
            <div className="flex justify-between mt-4">
              <button
                onClick={() => exportToExcelForItem(item)}
                className="text-blue-500 hover:text-blue-700"
              >
                <i className="fa-solid fa-file-excel"></i> Export to Excel
              </button>
              <button
                onClick={() => generatePDFForItem(item)}
                className="text-red-500 hover:text-red-700"
              >
                <i className="fa-solid fa-file-pdf"></i> Export to PDF
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default DashboardScreen;
